### ISSUE TITLE
Unexpected error fetching poolstation-None data

### ISSUE THREAD

**Issue by egtltd** [cibernox/homeassistant-poolstation#25]
When pool is off and can't read data take this error.

Unexpected error fetching poolstation-None data
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 354, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/poolstation/__init__.py", line 101, in _async_update_data
    await self.pool.sync_info()
  File "/usr/local/lib/python3.12/site-packages/pypoolstation/__init__.py", line 175, in sync_info
    self.percentage_electrolysis = int(info["vars"][API_SIGNS["percentage_electrolysis"]])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: invalid literal for int() with base 10: '---'

**Comment by cibernox** [comment]
Fixed by pypoolstation 0.8.0 (now the pinned version in the integration).

The traceback in this issue was the same as #41: an unguarded int() on a percentage_electrolysis value the API sometimes sends as '---', which raised ValueError and aborted the pool's whole sync every 60 seconds. 0.8.0 rewrites sync_info parsing so every numeric value is parsed independently with guarded to_float/to_int converters — a single malformed value can no longer take the pool offline.

The 'poolstation-None' name in the log line also no longer appears: the coordinator name now falls back to the pool id (pool.alias is only populated after the first sync).

Released: https://pypi.org/project/pypoolstation/0.8.0/
